# If you only wish to "use" vipersci with conda, you can just
# > conda env create -n vipersci -f environment.yml
#
# If you want to develop vipersci, do this:
# > conda create -n vipersci python=3.7
# > conda activate vipersci
# > conda env update -f environment_dev.yml
# > conda env update -f environment.yml
# If the last "update" takes forever, consider using "mamba" instead of "conda"
# for the update steps.
#
dependencies:
  - genshi
  - geopandas
  - numpy
  - pandas
  - pyproj
  - rasterio
  - scikit-image
  - scikit-learn
  - shapely
  - tifftools
