# Please read comments in environment.yml
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bump2version
  - cookiecutter
  - flake8
  - ipympl
  - jupyterlab
  - matplotlib
  - mypy
  - pytest
  - pytest-cov
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-apidoc
  - sphinxcontrib-autoprogram
  - tox
  - twine
